apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
    - image: fabribraguev/api-multiplica
      docker:
        dockerfile: ./Dockerfile.production
deploy:
  kubectl:
    manifests:
      - deploy/skaffold/dev/*